services:
  app:
    build: .
    depends_on:
      - db
    command: tail -f /dev/null
  db:
    image: mysql:9.4.0
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/docker-entrypoint-initdb.d/:ro