name: Cognate Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start containers
        run: docker compose up -d --build

      - name: List containers
        run: docker compose ps

      - name: Show app logs
        run: docker compose logs app

      - name: Wait for db ready
        run: |
          until docker compose exec db mysqladmin ping -h "db" --silent; do
            echo "Waiting for database..."
            sleep 2
          done

      - name: Run tests
        run: docker compose exec app python -m pytest tests
