name: Cognate Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker compose up -d --build

      - name: Wait for MySQL to be ready
        run: |
          until docker compose exec db mysqladmin ping -h "db" --silent; do
            echo "Waiting for database..."
            sleep 2
          done

      - name: Run tests
        run: docker compose exec app python -m pytest tests
